### ISSUE TITLE
[Feature] Ensure services discover each other via Service Discovery and not hard coded URLs

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/Movie#251]
**Is your feature request related to a problem? Please describe.**
In order to make service communication transparent, we need to ensure services do not depend upon each other using hard coded URLs. Instead, they should use a single domain name. 

**Describe the solution you'd like**
Services use domain name to discover each other. Also, the solution should not be too intrusive and should work smoothly with multiple frameworks i.e. Spring, vertx etc.

**Describe alternatives you've considered**
a) Netflix Eureka
b) Consul

**Additional context**

**Task Checklist**
- [ ] Explore how consul can be used
- [ ] Can vertx integrate with Consul
- [ ] Add docker container for Consul
- [ ] Be able to run all tests after introducing Consul
- [ ] Update architecture diagram
- [ ] Add architecture diagram to Readme
