### ISSUE TITLE
Byte stream metadata should be passed along with the movie details endpoint

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/Movie#32]
1. When byte stream metadata is passed for a movie along with its details as part of the following endpoints, then user should be able to upload video stream corresponding to that metadata later.

a. POST /user/movie
b. POST /user/{userId}/movie

2. For now, the metadata should be appended in the order provided by user and later on retrieved in the same order

3. Metadata stored by server
- Name
- Format (Should this be provided by the user or is there a way to determine the movie format from byte stream?)
- Size
- Upload Date
- Last Modification date

4. Locally, the video should be stored on the filesystem and hence a storage abstraction must be built which can be swapped for new implementations.

**Comment by Tyagi-Gaurav** [comment]
**TODO**

- [ ] Modify existing create movie endpoint to accept an optional byte stream
- [ ] Modify get movie to return metadata details (Excluding the byte stream)
- [ ] Modify delete to delete video and meta data details (Along with byte stream)
- [ ] Create abstraction to store video stream
- [ ] Need a way to detect the type of video
