### ISSUE TITLE
[Feature] Create a new go-based testing module which can be used to run load test on the application

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/Movie#368]
**Is your feature request related to a problem? Please describe.**
Would like to load test the application

**Describe the solution you'd like**
As a user, I would like to declare scenarios in a yaml file
The library should be able to pick up the data and generate the scenarios on the fly. 
To start with this could just be a simple scenario generator and a number of scenario runners.

**Describe alternatives you've considered**
Gatling is one of the frameworks that we could use, but this would be a nice practice.

**Additional context**

**Task Checklist**
- [ ] Come up with scenario file format
- [ ] Be able to read a function through a queue and run the scenario
- [ ] Be able to read the scenario file and generate a function that can be run by an executor
- [ ] Be able to capture the return code and record the latency
- [ ] Be able to capture number of success and failure
