### ISSUE TITLE
[TECH_TASK] Replace current app images with distroless images

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/Movie#389]
** What is the problem that we're trying to solve? **
We would like to reduce the size of images that are being used for docker in order to enable faster build times and less image download too.

**Task Checklist**
- [ ] Replace images for content-upload
- [ ] Replace images for Users
- [ ] Replace images for download

**How should this be released (Normal, Any Special Instructions) ?**
Should be released as normal PR and then merged to master

**Should this be monitored? If so, which metrics do we need?**
NA
