### ISSUE TITLE
[TECH_TASK] Migrate functional tests to GoLang

### ISSUE THREAD

**Issue by Tyagi-Gaurav** [Tyagi-Gaurav/Movie#390]
** What is the problem that we're trying to solve? **
Migrate functional tests to golang to avoid using same language/frameworks as prod code for running functional tests. 

** Are there multiple approaches? If so, please document below.**
yes, there are other approaches available, ie. using other languages or using other Java based frameworks. But this work is to be able to move away completely from Java based technologies. GoLang is chosen based on prior experience with that.

**Task Checklist**
- [ ] Create Golang functional test module - `functionalTestV2`
- [ ] Run functional test module along side other apps with a single test (healthcheck?).
- [ ] Migrate other tests

**How should this be released (Normal, Any Special Instructions) ?**
Normal

**Should this be monitored? If so, which metrics do we need?**
NA
